---
title: "ggplot2"
output: github_document
---

Look at size of the ggplot2 `VECTOR_ELT()` issue.

```{r}
library("rqdatatable")

# # load package facts
# cran <- tools::CRAN_package_db()
# cr <- tools::CRAN_check_results()
# saveRDS(list(cran = cran, cr = cr), "cran_facts_2019_03_31.RDS")
lst <- readRDS("cran_facts_2019_03_31.RDS")
cran <- lst$cran
cr <- lst$cr
```


```{r}
package_summary <- cr %.>%
  select_rows(.,
              !is.na(Status)) %.>%
  extend(., 
         one = 1) %.>%
  project(.,
          groupby = c("Package", "Status"),
          count = sum(one)) %.>%
  cdata::pivot_to_rowrecs(., 
                          columnToTakeKeysFrom = "Status",
                          columnToTakeValuesFrom = "count",
                          rowKeyColumns = "Package") %.>%
  extend(.,
         OK = ifelse(is.na(OK), 0, OK),
         NOTE = ifelse(is.na(NOTE), 0, NOTE),
         WARN = ifelse(is.na(WARN), 0, WARN),
         ERROR = ifelse(is.na(ERROR), 0, ERROR),
         FAIL = ifelse(is.na(FAIL), 0, FAIL)) %.>%
  extend(.,
         has_problem = (WARN + ERROR + FAIL)>0)
  
package_summary %.>% 
  head(.) %.>%
  knitr::kable(.)

# convert comma separated list into
# sequence of non-core package names
parse_lists <- function(strs) {
  strs[is.na(strs)] <- ""
  strs <- gsub("[(][^)]*[)]", "", strs)
  strs <- gsub("\\s+", "", strs)
  strs <- strsplit(strs, ",", fixed=TRUE)
  strs <- lapply(
    strs,
    function(si) {
      setdiff(si, c("", "R", 
                    "base", "compiler", "datasets", 
                    "graphics", "grDevices", "grid",
                    "methods", "parallel", "splines", 
                    "stats", "stats4", "tcltk", "tools",
                    "translations", "utils"))
    })
  strs
}

# collect the columns we want
d <- data.frame(
  Package = cran$Package,
  stringsAsFactors = FALSE)
d$Depends <- parse_lists(cran$Depends)
d$nDepends <- vapply(d$Depends, length, numeric(1))
d$Imports <- parse_lists(cran$Imports)
d$nImports <- vapply(d$Imports, length, numeric(1))
d$Suggests <- parse_lists(cran$Suggests)
d$nSuggests <- vapply(d$Suggests, length, numeric(1))

d$Depends_ggplot2 <- vapply(d$Depends, 
                            function(di) {
                              "ggplot2" %in% di
                            }, logical(1))
summary(d$Depends_ggplot2)

d$Imports_ggplot2 <- vapply(d$Imports, 
                            function(di) {
                              "ggplot2" %in% di
                            }, logical(1))
summary(d$Imports_ggplot2)

d$Suggests_ggplot2 <- vapply(d$Suggests, 
                            function(di) {
                              "ggplot2" %in% di
                            }, logical(1))
summary(d$Suggests_ggplot2)

d <- d[, c("Package", "nDepends", "nImports", "nSuggests",
           "Depends_ggplot2", "Imports_ggplot2", "Suggests_ggplot2")]

d %.>%
  extend(., one = 1) %.>%
  project(., 
          groupby = qc(Depends_ggplot2, Imports_ggplot2, Suggests_ggplot2),
          count = sum(one)) %.>% 
  knitr::kable(.)

# map check status into our data
nrow(d)
d <- natural_join(d, package_summary, 
                  by = "Package", 
                  jointype = "INNER")
(npackages <- nrow(d))

d %.>%
  extend(., 
         one = 1,
         uses_ggplot2 = (Depends_ggplot2 + Imports_ggplot2 + Suggests_ggplot2)>0) %.>%
  project(., 
          groupby = qc(uses_ggplot2, has_problem),
          count = sum(one)) %.>% 
  extend(., 
         fraction = count/sum(count)) %.>%
  knitr::kable(.)

model <- glm(has_problem ~ Depends_ggplot2 + Imports_ggplot2 + Suggests_ggplot2, 
             data = d, 
             family = binomial)
summary(model)
```
