---
title: "show versioned data"
output: html_document
date: "2024-09-19"
---


```{r}
library(DBI)
library(RSQLite)
source("pull_data_by_use.R")
```

```{r}
con <- dbConnect(
  RSQLite::SQLite(), 
  "movie_data.sqlite", 
  flags=SQLITE_RO)
```


```{r}
dbGetQuery(
  con, 
  "SELECT * from update_log ORDER BY _usi") |>
  knitr::kable()
```

```{r}
dbGetQuery(
  con, 
  "SELECT * from d_data_log ORDER BY _fi, _usi LIMIT 6") |>
  knitr::kable()
```


```{r}
usi_before_August = dbGetQuery(
  con, 
  "SELECT MAX(_usi) FROM update_log WHERE as_of_date == '2024-07-31'")[1, 1]

usi_before_August
```


[query](https://github.com/WinVector/Examples/blob/main/versioning_data/pull_data_by_use.R).

```{r comment=NA}
writeLines(pull_data_by_usi(usi_before_August))
```

```{r}
d_before_August <- dbGetQuery(
  con, 
  pull_data_by_usi(usi_before_August))
```


```{r}
d_before_August |>
  head(n=3) |>
  knitr::kable()
```


```{r}
usi_after_August = dbGetQuery(
  con, 
  "SELECT MAX(_usi) FROM update_log WHERE as_of_date == '2024-08-31'")[1, 1]

usi_after_August
```

```{r}
d_after_August <- dbGetQuery(
  con, 
  pull_data_by_usi(usi_after_August))
```


```{r}
d_after_August |>
  head(n=3) |>
  knitr::kable()
```


```{r}
dbGetQuery(
  con, 
  "SELECT * FROM d_row_deletions ORDER BY _usi, _fi") |>
  knitr::kable()
```



```{r}
dbDisconnect(con)
```
