---
title: "traj_graph_2"
output: github_document
date: "2024-06-23"
---

```{r}
library(ggplot2)
library(data.table)
library(wrapr)
set.seed(2024)
```




```{r}
build_traj <- function(d_ex, lambda_max = 3, length.out = 100) {
    frame <- list()
    model_coefs <- NULL
    suppressWarnings(
      for(lambda in seq(0, lambda_max, length.out = length.out)) {
        model <- glm(y ~ x1 + x2, family=binomial(), data=d_ex, weights = 1 + lambda * d_ex$y)
        model_coefs <- coef(model)
        preds <- predict(model, type='response', newdata=d_ex)
        row_frame <- as.data.frame(t(as.matrix(preds)))
        row_frame['lambda'] <- lambda
        frame <- c(frame, list(row_frame))
      }
    )
    frame <- do.call(rbind, frame)
    return(list(frame=frame, model_coefs=model_coefs))
}
```


```{r}
plot_traj_graph <- function(d_ex, ..., lambda_max = 3, title = '') {
  to[frame, model_coefs] <- build_traj(d_ex, lambda_max = lambda_max)
  plot_dat <- data.frame(data.table::melt(
    data.table(frame), 
    variable.name = 'row',
    value.name = 'score',
    id.vars='lambda'))
  g <- ggplot(
    data=plot_dat,
    mapping=aes(x=lambda, y=score, color=row, shape=row)
  ) +
    geom_line(alpha=0.5) +
    geom_point(alpha=0.5) +
    ggtitle(title)
  return(list(plot=g, model_coefs=model_coefs))
}
```



```{r}
d_ex_1 <- wrapr::build_frame(
   "x1"  , "x2", "y" |
     0   , 0   , 0   |
     1   , 0   , 1   |
     -2  , 0   , 0   |
     0   , 2   , 1   |
     1   , 2   , 1   |
     1   , 1   , 0   )
```

```{r}
to[plot, model_coefs] <- plot_traj_graph(d_ex_1, title='ex_1')
print(model_coefs)
plot
```


```{r}
 d_ex_2 <- wrapr::build_frame(
    "x1"  , "x2", "x3", "x4", "y"   |
      -4L ,  4L ,  0L , -2L , TRUE  |
       3L , -5L , -1L , -1L , TRUE  |
       1L , -3L , -1L , -3L , TRUE  |
      -5L , -2L , -3L , -5L , TRUE  |
       4L , -3L ,  1L , -5L , FALSE |
      -1L ,  3L ,  2L , -3L , TRUE  |
       2L ,  2L , -2L , -2L , FALSE |
      -5L ,  3L , -3L ,  5L , TRUE  |
       5L ,  5L , -1L , -1L , FALSE |
      -2L , -5L ,  2L , -4L , FALSE )
```


```{r}
to[plot, model_coefs] <- plot_traj_graph(d_ex_2, title='ex_2')
print(model_coefs)
plot
```



```{r}
d_ex_3 <- wrapr::build_frame(
   "x1"  , "x2", "y" |
     0   , 0   , 0   |
     1   , 0   , 1   |
     0   , 1   , 1   |
     1   , 1   , 0   |
     -1  , 1   , 0   |
     1   , -1  , 0   )
```



```{r}
to[plot, model_coefs] <- plot_traj_graph(d_ex_3, lambda_max = 1000, title='ex_3')
print(model_coefs)
plot
```


```{r}
want_frame <- function(frame) {
  check_eps = 0.03
  n_f_rows <- nrow(frame)
  have_cross <- FALSE
  have_increasing <- FALSE
  have_decreasing <- FALSE
  have_non_monotone <- FALSE
  for(col in colnames(frame)) {
    if(col != 'lambda') {
      col_v <- frame[[col]]
      have_increasing <- have_increasing || ((col_v[[1]] + check_eps) < col_v[[n_f_rows]])
      have_decreasing <- have_decreasing || ((col_v[[1]] - check_eps) > col_v[[n_f_rows]])
      have_non_monotone <- have_non_monotone || (min(col_v) + check_eps < min(col_v[[1]], col_v[[n_f_rows]])) || (max(col_v) - check_eps > max(col_v[[1]], col_v[[n_f_rows]])) 
      for(col2 in colnames(frame)) {
        if(col2 != 'lambda') {
          col2_v <- frame[[col2]]
          see_cross <- (abs(col_v[[1]] - col2_v[[1]]) > check_eps) && (abs(col_v[[n_f_rows]] - col2_v[[n_f_rows]]) > check_eps) && (col_v[[n_f_rows]] != col2_v[[n_f_rows]]) && ((col_v[[1]] > col2_v[[1]]) != (col_v[[n_f_rows]] > col2_v[[n_f_rows]]))
          have_cross <- have_cross || see_cross
        }
      }
    }
  }
  return(have_increasing && have_decreasing && have_cross)
}
```




```{r}
mk_example <- function() {
  d_cols <- c('x1', 'x2', 'y')
  n_rows <- 10
  while(TRUE) {
    d_ex <- data.frame(matrix(
      sample(seq(-20, 20), size = length(d_cols) * n_rows, replace = TRUE),
      ncol=length(d_cols)))
    colnames(d_ex) <- d_cols
    d_ex['y'] = d_ex['y'] >= 0
    to[frame, model_coefs] <- build_traj(d_ex)
    if(want_frame(frame)) {
      return(d_ex)
    }
  }
}

```


```{r}
d_ex <- mk_example()
```

```{r}
cat(wrapr::draw_frame(d_ex))
```

```{r}
knitr::kable(d_ex)
```


```{r}
to[plot, model_coefs] <- plot_traj_graph(d_ex, title='ex')
print(model_coefs)
plot
```


```{r}
w_1 <- rep(1, nrow(d_ex))
model_1 <- glm(
  y ~ x1 + x2, 
  family=binomial(), 
  data=d_ex, 
  weights = w_1)
soln_1 <- coef(model_1)

soln_1
```


```{r}
eps <- 1e-5
w_2 <- w_1 + eps * d_ex$y
model_2 <- glm(
  y ~ x1 + x2, 
  family=binomial(), 
  data=d_ex, 
  weights = w_2)
soln_2 <- coef(model_2)

soln_2
```

```{r}
diff <- (soln_2 - soln_1) / eps

diff
```


```{r}
w <- w_1
p <- predict(model_1, type='response', newdata=d_ex)
y <- as.numeric(d_ex[['y']])
sum_M = matrix(0, nrow=3, ncol=3)
sum_V = rep(0, 3)
for(i in seq(nrow(d_ex))){
  x_i <- c(1, as.numeric(d_ex[i, c('x1', 'x2')]))
  sum_M <- sum_M + w[[i]] * p[[i]] * (1 - p[[i]]) * (x_i %*% t(x_i))
  sum_V <- sum_V + y[[i]] * (y[[i]] - p[[i]]) * x_i
}
b <- solve(sum_M, sum_V)

b
```


