---
title: "CodingExampleR1"
author: "Win-Vector LLC"
date: "December 25, 2015"
output: html_document
---

```{r startup, echo=FALSE, results='hide', warning=FALSE, message=FALSE}
source('utils.R')
source('modelR.R')
source('mkExample.R')
source('bindValues.R')
sourcedFns <- ls()
# devtools::install_github("WinVector/WVPlots")
library("WVPlots")
# devtools::install_github('WinVector/vtreat')
library('vtreat')
options(gsubfn.engine = "R")
library('sqldf')
cl <- parallel::makeCluster(parallel::detectCores())
```


```{r define, echo=FALSE, results='hide', warning=FALSE, message=FALSE}
yVars <- c('yCat','yNumeric')
yName <- 'yNumeric'


set.seed(232567)
vX1 <- designVar('x1',10)
vN1 <- designNoiseVar('n1',500)


runBigExpmt <- function(expmt) {
  set.seed(232567)
  vplan <- expmt$vplan
  fnFitter <- expmt$fnFitter
  eName <- expmt$eName
  
  print("*************************************************************")
  print(eName)
  
  dTrain <- generateExample(vplan,2000)  # Training set
  vars <- setdiff(colnames(dTrain),yVars)
  dCal <- generateExample(vplan,10000)   # Used to pick sigma
  dTest <- generateExample(vplan,10000)  # Pure holdout test
  
  bSigmaBest <- findSigmaR(cl,
                           fnFitter,
                          yName,
                          yVars,
                          dTrain,
                          vars,
                          dCal) 
  
  print(paste('bSigmaBest',bSigmaBest))
  
  
  
  print('naive effects model')
  bCoder <- trainEffectCoderR(dTrain,yName,vars,0)
  dTrainB <- bCoder$codeFrameR(dTrain)
  dTestB <- bCoder$codeFrameR(dTest)
  varsB <- setdiff(colnames(dTrainB),yVars)
  preds <- fnFitter(yName,varsB,dTrainB,dTestB,
                    what=paste(eName,'naive effects model'),
                    verbose=TRUE)
  dTrainB$pred <- preds$trainPred
  print(paste(eName,'naive effects model train rmse',
              rmse(dTrainB$pred,dTrainB[[yName]])))
  print(WVPlots::ScatterHist(dTrainB,'pred',yName,
                             paste(eName,
                                   'naive effects model train',
                                   sep='\n'),
                             smoothmethod='lm',annot_size=2))
  dTestB$pred <- preds$appPred
  print(paste(eName,
              'naive effects model test rmse',
              rmse(dTestB$pred,dTestB[[yName]])))
  print(WVPlots::ScatterHist(dTestB,'pred',yName,
                             paste(eName,
                                   'naive effects model test',
                                   sep='\n'),
                             smoothmethod='lm',annot_size=2))
  
  
  print(paste('effects model, sigma=',bSigmaBest))
  bCoder <- trainEffectCoderR(dTrain,yName,vars,bSigmaBest)
  dTrainB <- bCoder$codeFrameR(dTrain)
  dTestB <- bCoder$codeFrameR(dTest)
  varsB <- setdiff(colnames(dTrainB),yVars)
  preds <- fnFitter(yName,varsB,dTrainB,dTestB,
                    what=paste(eName,'effects model, sigma=',bSigmaBest),
                    verbose=TRUE)
  dTrainB$pred <- preds$trainPred
  print(paste(eName,
              'Noised',bSigmaBest,'train rmse',
              rmse(dTrainB$pred,dTrainB[[yName]])))
  print(WVPlots::ScatterHist(dTrainB,'pred',yName,
                             paste(eName,
                                   '\neffects model train, sigma=',
                                   bSigmaBest),
                             smoothmethod='lm',annot_size=2))
  dTestB$pred <- preds$appPred
  print(paste(eName,
              'Noised',bSigmaBest,'test rmse',
              rmse(dTestB$pred,dTestB[[yName]])))
  print(WVPlots::ScatterHist(dTestB,'pred',yName,
                             paste(eName,
                                   '\neffects model test, sigma=',
                                   bSigmaBest),
                             smoothmethod='lm',annot_size=2))
  
  
  print('effects model, jacknifed')
  bCoder <- trainEffectCoderR(dTrain,yName,vars,0)
  # dTrainB <- bCoder$codeFrame(dTrain)
  # dTrainB <- bCoder$codeFrame(dCal)
  dTrainB <- jackknifeEffectCodeR(dTrain,yName,vars)
  dTestB <- bCoder$codeFrameR(dTest)
  varsB <- setdiff(colnames(dTrainB),yVars)
  preds <- fnFitter(yName,varsB,dTrainB,dTestB,
                     what=paste(eName,'effects model, jackknifed'),
                    verbose=TRUE)
  dTrainB$pred <- preds$trainPred
  print(paste(eName,
              'jackknifed train rmse',
              rmse(dTrainB$pred,dTrainB[[yName]])))
  print(WVPlots::ScatterHist(dTrainB,'pred',yName,
                             paste(eName,
                                   'effects model train, jackknifed',
                                   sep='\n'),
                             smoothmethod='lm',annot_size=2))
  dTestB$pred <- preds$appPred
  print(paste(eName,
              'jackknifed test rmse',
              rmse(dTestB$pred,dTestB[[yName]])))
  print(WVPlots::ScatterHist(dTestB,'pred',yName,
                             paste(eName,
                                   'effects model test, jackknifed',
                                   sep='\n'),
                             smoothmethod='lm',annot_size=2))
  
  
  mkExpmtRunner <- function(vplan) {
    force(vplan)
    bindToEnv(objNames=sourcedFns,
              sourcedFns,
              fnFitter)
    function(repID) {
      # set up experiment
      yVars <- c('yCat','yNumeric')
      yName <- 'yNumeric'
      dTrain <- generateExample(vplan,2000)  # Training set
      vars <- setdiff(colnames(dTrain),yVars)
      dCal <- generateExample(vplan,10000)   # Used to pick sigma
      dTest <- generateExample(vplan,10000)  # Pure holdout test
      
      # run naive mode
      bCoder <- trainEffectCoderR(dTrain,yName,vars,0)
      dTrainB <- bCoder$codeFrameR(dTrain)
      dTestB <- bCoder$codeFrameR(dTest)
      varsB <- setdiff(colnames(dTrainB),yVars)
      preds <- fnFitter(yName,varsB,dTrainB,dTestB) 
      dTrainB$pred <- preds$trainPred
      trainRMSE <- rmse(dTrainB$pred,dTrainB[[yName]])
      dTestB$pred <- preds$appPred
      testRMSE <- rmse(dTestB$pred,dTestB[[yName]])
      f1 <- data.frame(repID=repID,
                       bSigmaBest=NA,
                       what='NaiveModel',
                       trainRMSE=trainRMSE,
                       testRMSE=testRMSE,
                       stringsAsFactors = FALSE)
      
      # sigma model
      bSigmaBest <- findSigmaR(NULL,
                               fnFitter,
                              yName,
                              yVars,
                              dTrain,
                              vars,
                              dCal) 
      bCoder <- trainEffectCoderR(dTrain,yName,vars,bSigmaBest)
      dTrainB <- bCoder$codeFrameR(dTrain)
      dTestB <- bCoder$codeFrameR(dTest)
      varsB <- setdiff(colnames(dTrainB),yVars)
      preds <- fnFitter(yName,varsB,dTrainB,dTestB) 
      dTrainB$pred <- preds$trainPred
      trainRMSE <- rmse(dTrainB$pred,dTrainB[[yName]])
      dTestB$pred <- preds$appPred
      testRMSE <- rmse(dTestB$pred,dTestB[[yName]])
      f2 <- data.frame(repID=repID,
                       bSigmaBest=bSigmaBest,
                       what='NoisedModel',
                       trainRMSE=trainRMSE,
                       testRMSE=testRMSE,
                       stringsAsFactors = FALSE)
      
      # jackknifed model
      bCoder <- trainEffectCoderR(dTrain,yName,vars,0)
      dTrainB <- jackknifeEffectCodeR(dTrain,yName,vars)
      dTestB <- bCoder$codeFrameR(dTest)
      varsB <- setdiff(colnames(dTrainB),yVars)
      preds <- fnFitter(yName,varsB,dTrainB,dTestB) 
      dTrainB$pred <- preds$trainPred
      trainRMSE <- rmse(dTrainB$pred,dTrainB[[yName]])
      dTestB$pred <- preds$appPred
      testRMSE <- rmse(dTestB$pred,dTestB[[yName]])
      f3 <- data.frame(repID=repID,
                       bSigmaBest=NA,
                       what='JackknifeModel',
                       trainRMSE=trainRMSE,
                       testRMSE=testRMSE,
                       stringsAsFactors = FALSE)
      rbind(f1,f2,f3)
    }
  }
  
  eworker <- mkExpmtRunner(vplan)
  res <- parallel::parLapplyLB(cl,1:100,eworker)
  res <- do.call(rbind,res)
  
  print(ggplot(data=res,aes(x=testRMSE,color=what)) +
    geom_density(adjust=0.5,trim=TRUE) + 
    ggtitle(paste(eName,'test RMSE, noised model',sep='\n')))
  
  for(w in sort(unique(res$what))) {
    print("********")
    print(paste(eName,w))
    ri <- res[res$what==w,]
    print(summary(ri$testRMSE))
    print(sqrt(var(ri$testRMSE)))
    print("********")
  }
  
  rm <- sqldf('
   SELECT
      rJ.repID,
      rN.testRMSE - rJ.testRMSE NrmseMinusJrmse,
      rN.testRMSE nTestRMSE,
      rJ.testRMSE jTestRMSE,
      rN.bSigmaBest
   FROM
      res rJ
   JOIN
      res rN
   ON
      rJ.repID=rN.repID
   WHERE
      rJ.what="JackknifeModel" AND
      rN.what="NoisedModel"
   ')
  
  print(ggplot(data=rm,aes(x=NrmseMinusJrmse)) +
    geom_density(adjust=0.5,trim=TRUE) + 
    ggtitle(paste(eName,'noise test RMSE minus jackknife test RMSE',
                  sep='\n')))
  
  print(ggplot(data=res[res$what=='NoisedModel',],aes(x=bSigmaBest)) +
    geom_density(adjust=0.5) +
      ggtitle(eName))
  
  print(ggplot(data=rm,aes(x=nTestRMSE,y=jTestRMSE)) +
    geom_point() +
    geom_abline(slope=1,intercept=0) +
    coord_fixed() +
    ggtitle(paste(eName,
                  'noised model performance versus jackknifed model performance',
                  sep='\n')))
  
  print("*************************************************************")
}
```

*****

one noise variable, linear regression
-------------

```{r nvlr, echo=FALSE, warning=FALSE, message=FALSE}
runBigExpmt(list(vplan=list(vN1),fnFitter=lrFitter,
                 eName="one noise variable, linear regression"))
```

*****

one variable, linear regression
-------------

```{r ovlr, echo=FALSE, warning=FALSE, message=FALSE}
runBigExpmt(list(vplan=list(vX1),fnFitter=lrFitter,
                 eName="one variable, linear regression"))
```


*****

one variable plus noise variable, linear regression
-------------

```{r ovnlr, echo=FALSE, warning=FALSE, message=FALSE}
runBigExpmt(list(vplan=list(vX1,vN1),fnFitter=lrFitter,
                 eName="one variable plus noise variable, linear regression"))
```


*****

one variable plus noise variable, diagonal regression
-------------

```{r ovndr, echo=FALSE, warning=FALSE, message=FALSE}
runBigExpmt(list(vplan=list(vX1,vN1),fnFitter=dFitter,
                 eName="one variable plus noise variable, diagonal regression"))
```

*****

```{r shutdown, echo=FALSE, results='hide', warning=FALSE, message=FALSE}
if(!is.null(cl)) {
  parallel::stopCluster(cl)
  cl <- NULL
}
```
