<h1 id="what-good-is-analysis-of-variance">What Good is Analysis of Variance?</h1>
<p>2024-02-19</p>
<h2 id="introduction">Introduction</h2>
<p>I'd like to demonstrate what "analysis of variance" (often abbreviated as "anova" or "aov") does for you as a data scientist or analyst. After reading this note you should be able to determine how an analysis of variance style calculation can or can not help with your project.</p>
<center>
<img src="McB-01.jpg"/>
<p/>
(Orson Welles as Macbeth, a photo that will be made relevant in the conclusion)
</center>
<p>We will exhibit specific examples, in <a href="https://www.r-project.org"><code>R</code></a>, designed to trigger most of the issues we are worried about <em>all at the same time</em>. In practice (for data sets with large meaningful signal, relations, or correlations) not everything we are worried about tends to fail at the same time. However, it is quite instructive to see everything go wrong at the same time.</p>
<p>We will show the exact calculations performed, beyond saying "call <code>aov()</code>". This isn't to discuss the implementation, which we trust, but to make clear what the reported statistics are. This lets us confirm that the current <code>R</code> <code>aov()</code> calculations do in fact organize the data in the manner Fisher described (which is not in fact obvious from trying to read the source code).</p>
<p>We will also discuss some of the difficulty in pinning down the intent and meaning of analysis of variance in a discussion section.</p>
<h2 id="analysis-of-variance">Analysis of Variance</h2>
<p>Analysis of variance comes to many of us from works derived from R. A. Fisher *Statistical Methods for Research Workers(, Oliver and Boyd, 1925. In chapter VII "Intraclass Correlations and the Analysis of Variance" Fisher writes:</p>
<blockquote>
<p>If <code>k</code> is the number in each class, then each set of <code>k</code> values will provide <code>k (k - 1)</code> values for the symmetrical table, which thus may contain an enormous number entries, and be very laborious to construct. To obviate this difficulty Harris introduced an abbreviated method of calculation by which the value of the correlation given by the symmetrical table may be obtained directly from two distributions.</p>
</blockquote>
<p>Roughly, Fisher is saying that Harris (1916) suggests evaluating the quality and significance of a model fit from a small number of summaries or statistics. This is a more sensitive method than a common naive idea of attempting to attribute model fit and model quality down to specific levels of variables.</p>
<p>In such early examples we have:</p>
<ul>
<li>A regression problem, or a numeric valued variable we are trying to predict (called the dependent variable or outcome).</li>
<li>One or more category or string-valued explanatory variables with a fixed set of values or levels. This reduces the numeric prediction or regression problem to a partitioning problem or evaluating clustering quality.</li>
<li>The decision to use square error as a loss function. Larger square error is bad, and small square error is good.</li>
<li>A single test statistic or summary. In this case the statistic is: measured reduction (as a ratio) of square error or variance. This statistic allows a calculation of significance of result through an <a href="https://en.wikipedia.org/wiki/F-test">F-test</a>.</li>
<li>The decision to use adjustments of "in sample" statistics to determine model quality. This differs from the more general (though much more computationally expensive) practice of test data, hold out data, or <a href="https://win-vector.com/2020/03/10/cross-methods-are-a-leak-variance-trade-off/">cross methods</a> (including cross validation). Such adjustments are reliable for linear models (where the <a href="https://win-vector.com/2023/03/16/bounding-excess-generalization-error-for-linear-regression-models/">model over-fit is bounded by "degrees of freedom"</a>, but are not always applicable to more general models (including trees and neural nets).</li>
</ul>
<p>Analysis of variance quickly got generalized past the above to include arbitrary nested models (instead of only categorical variables), detailed attribution of model performance to groups of variables, and classification models (through dispersion measures such as <a href="https://en.wikipedia.org/wiki/Deviance_(statistics)">statistical deviance</a>). However, key ideas and terminology originate in the categorical or partitioning case.</p>
<h3 id="an-analysis-of-variance-example-where-there-is-no-signal">An Analysis of Variance Example, Where There is No Signal</h3>
<p>Let's try analysis of variance with current tools.</p>
<p>First we set up a data set with a dependent or outcome variable "<code>y</code>" and a single categorical explanatory variable "<code>group</code>". For this first example we deliberately design the variable <code>group</code> to be useless and generated independently of <code>y</code> (which we, through a very slight abuse of terminology call "the null situation").</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># seed pseudo-random generator for replicability</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2024</span>)</span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pick our number of data rows</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># this is a large number to dispel:</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  &quot;you only run into statistical problems with small data&quot;</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>m_row <span class="ot">&lt;-</span> <span class="dv">100000</span></span></code></pre></div>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pick the k=100 levels or values for our explanatory variable</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># this is a small number in some applications</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>group_levels <span class="ot">&lt;-</span> <span class="fu">sprintf</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">&quot;level_%03d&quot;</span>, <span class="fu">seq</span>(<span class="dv">100</span>))</span></code></pre></div>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># build our data</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>d_null <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="fu">sample</span>(</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    group_levels, </span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> m_row, </span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>d_null<span class="sc">$</span>y <span class="ot">&lt;-</span> <span class="dv">10</span> <span class="sc">*</span> <span class="fu">rnorm</span>(<span class="at">n =</span> m_row)</span></code></pre></div>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># show a bit of our data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(d_null))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th style="text-align: left;">group</th>
<th style="text-align: right;">y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">level_066</td>
<td style="text-align: right;">-3.523702</td>
</tr>
<tr class="even">
<td style="text-align: left;">level_037</td>
<td style="text-align: right;">16.144303</td>
</tr>
<tr class="odd">
<td style="text-align: left;">level_045</td>
<td style="text-align: right;">6.997154</td>
</tr>
<tr class="even">
<td style="text-align: left;">level_060</td>
<td style="text-align: right;">-3.063851</td>
</tr>
<tr class="odd">
<td style="text-align: left;">level_017</td>
<td style="text-align: right;">5.519029</td>
</tr>
<tr class="even">
<td style="text-align: left;">level_032</td>
<td style="text-align: right;">-2.761535</td>
</tr>
</tbody>
</table>
<p>We are now ready to perform our analysis of variance.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  y <span class="sc">~</span> group,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> d_null))</span></code></pre></div>
<pre><code>##                Df  Sum Sq Mean Sq F value Pr(&gt;F)
## group          99    8638   87.25   0.872  0.813
## Residuals   99900 9991165  100.01</code></pre>
<p>The above report has columns summarizing facts about:</p>
<ul>
<li><code>Df</code>: the "degrees of freedom." This is the unit of measure for examples, instances, and even coefficients and variables. We will include a small section on this concept later.</li>
<li><code>Sum sq</code>: the sum of squares, what is colloquially called the variances.</li>
<li><code>Mean Sq</code>: <code>(Sum Sq) / Df</code>. This is a "bias corrected" variance estimate.</li>
<li><code>F value</code>: the statistic mentioned by Fisher. In fact this is the F-statistic, a random variable that is distributed as we would expect the ratio of two variances to be distributed. Technically it is distributed as the ratio of two chi-square distributions (<a href="https://en.wikipedia.org/wiki/F-distribution">ref</a>), which in turn are distributed as sums of squares of normally distributed random variables. All this machinery is to give us a distribution that lets us estimate if an observed ratio of two variances (or sums of squares) is considered large or small. We want this value to be above 1.</li>
<li><code>Pr(&gt;F)</code>: the significance of the observed <code>F value</code>. Values near zero mean our observed F value is large enough to be <em>not</em> often produced by mere sampling phenomena. This is then taken as evidence of a good model fit. Be aware "highly significant" means a significance near zero, not a large one. Also, significance is merely the chance of seeing a signal as least as strong as observed, <em>assuming</em> the signal was due to sampling error. A significance is only the estimate probability of one type of error, and there are many more ways than one to go wrong in modeling. A significance is very much <strong>NOT</strong> one minus the chance we have a good fit!!!</li>
</ul>
<p>The rows of the report show:</p>
<ul>
<li><code>group</code>: our categorical variable.
<ul>
<li><code>Df = 99</code>, means that <code>group</code> consumes 99 "degrees of freedom". This comes from the fact that the 100 possible levels for the categorical variable <code>group</code> get expanded into 100 different numeric indicator variables during analysis. One is subtracted as there is a linear dependence in this re-encoding.</li>
<li><code>Sum Sq = 8638</code> means the analysis of variance is crediting the variable <code>group</code> with 8638 units of variance explained. We want this to be large.</li>
<li><code>F value = 0.872</code>. The F value is how much reduction in square difference or variance we are seeing. We want this to be greater than 1.</li>
<li><code>Pr(&gt;F) = 0.813</code> means a sampling process where there is no relation between <code>group</code> and <code>y</code> can produce an F value as large as observed 81.3% of the time. This non-significance is the measure of how uninteresting this F value is.</li>
</ul></li>
<li><code>Residuals</code>: the variation unexplained by the model.
<ul>
<li><code>Df</code>: the number of example or instance rows in the data set minus the <code>Df</code> of all the variables (again minus 1). The idea is: each variable could be used to fix the answer of a single row, so this is how many somewhat novel rows our model was tried on. We want this to be large.</li>
<li><code>Sum Sq</code>: the unexplained variance. We want this to be small.</li>
</ul></li>
</ul>
<p>The data set we analyzed has no relation, so the poor opinion on model quality expressed by the analysis of variance is exactly the correct determination.</p>
<h4 id="degrees-of-freedom">Degrees of Freedom</h4>
<p>"Degrees of freedom" is a unit of "how many examples is one looking at?" Roughly think of degrees of freedom as: "number of opportunities to be wrong."</p>
<p>For a data set the degrees of freedom is the number of data rows or example instances. We usually use the number of rows minus 1, as we are usually assuming we start with an estimate of the average or mean of the data (consuming 1 degree of freedom).</p>
<p>For a linear model: the degrees of freedom is the number of model coefficients, which in turn corresponds to the number of <em>numeric</em> variables. For categorical variables we get one degree of freedom per level or possible categorical value, minus one (due to the linear dependence in the usual method of expanding categorical variables to 0/1 indicator variables).</p>
<p>In linear models over data: we tend to lose one degree of freedom per fitted coefficient in the model (<a href="https://win-vector.com/2023/03/16/bounding-excess-generalization-error-for-linear-regression-models/">ref</a>. It is this <em>arbitrage</em> in counting that lets us use degrees of freedom to count variables or coefficients in addition to instances.</p>
<p>Roughly: we get degrees of freedom by inspection. For data and linear models, degrees of freedom is a matter of counting. Getting the number exactly right (within <code>+-1</code>) can be a <em>very</em> contentious discussion. Fortunately, for large data sets and large numbers of variables "close is good enough" in specifying the degrees of freedom.</p>
<h4 id="the-calculations">The Calculations</h4>
<p>Let's directly calculate all of the items in the analysis of variance table. This code will be much less general than R's <code>aov()</code>, but can show us exactly what is going on in a simple "single categorical variable" (or clustering) case.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute analysis of variance of dependent variable y</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># clustered by categorical explanatory variable group</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>aov_by_hand <span class="ot">&lt;-</span> <span class="cf">function</span>(y, group) {</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># get observed group means</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  observed_effects <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    y,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">list</span>(group),</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">FUN =</span> mean)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># build a group to effect lookup table</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  oe <span class="ot">&lt;-</span> observed_effects[, <span class="dv">2</span>, drop <span class="ot">=</span> <span class="cn">TRUE</span>]</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>(oe) <span class="ot">&lt;-</span> observed_effects[, <span class="dv">1</span>, drop <span class="ot">=</span> <span class="cn">TRUE</span>]</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># calculate components of analysis of variance table</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># declare degrees of freedom</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  df_group <span class="ot">&lt;-</span> <span class="fu">length</span>(oe) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  df_residual <span class="ot">&lt;-</span> <span class="fu">length</span>(y) <span class="sc">-</span> df_group <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># get sums of square differences</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  group_sq <span class="ot">&lt;-</span> <span class="fu">sum</span>(  <span class="co"># what is traditional</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>    (oe[group] <span class="sc">-</span> <span class="fu">mean</span>(y))<span class="sc">**</span><span class="dv">2</span>)  </span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>  model_improvement <span class="ot">&lt;-</span> ( <span class="co"># what we care about</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sum</span>((y <span class="sc">-</span> <span class="fu">mean</span>(y))<span class="sc">**</span><span class="dv">2</span>) <span class="sc">-</span> <span class="fu">sum</span>((y <span class="sc">-</span> oe[group])<span class="sc">**</span><span class="dv">2</span>))  </span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stopifnot</span>(<span class="fu">abs</span>(group_sq <span class="sc">-</span> model_improvement) <span class="sc">&lt;</span> <span class="fl">1e-8</span>)  <span class="co"># confirm equal</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>  residual_sq <span class="ot">&lt;-</span> <span class="fu">sum</span>((y <span class="sc">-</span> oe[group])<span class="sc">**</span><span class="dv">2</span>)  <span class="co"># unexplained variation</span></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># get the averages, un-biasing the estimate by dividing by degrees</span></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># of freedom instead of number of instances</span></span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>  group_mean_sq <span class="ot">&lt;-</span> group_sq <span class="sc">/</span> df_group</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>  residual_mean_sq <span class="ot">&lt;-</span> residual_sq <span class="sc">/</span> df_residual</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>  <span class="co"># calculate the test statistic</span></span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>  F_value <span class="ot">&lt;-</span> group_mean_sq <span class="sc">/</span> residual_mean_sq</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>  <span class="co"># compute the significance of the test statistic</span></span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>  <span class="co"># this is essentially a table lookup or special function</span></span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>  group_sig <span class="ot">&lt;-</span> <span class="fu">pf</span>(</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>    F_value, </span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>    df_group, </span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>    df_residual, </span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>  <span class="co"># wrap report into a data frame</span></span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a>  anova_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Df</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(df_group, df_residual),</span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Sum Sq</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(group_sq, residual_sq),</span>
<span id="cb8-40"><a href="#cb8-40" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Mean Sq</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(group_mean_sq, residual_mean_sq),</span>
<span id="cb8-41"><a href="#cb8-41" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">F value</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(F_value, <span class="cn">NA</span>),</span>
<span id="cb8-42"><a href="#cb8-42" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Pr(&gt;F)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(group_sig, <span class="cn">NA</span>),</span>
<span id="cb8-43"><a href="#cb8-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">check.names =</span> <span class="cn">FALSE</span></span>
<span id="cb8-44"><a href="#cb8-44" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb8-45"><a href="#cb8-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row.names</span>(anova_table) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;group&quot;</span>, <span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb8-46"><a href="#cb8-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(anova_table)</span>
<span id="cb8-47"><a href="#cb8-47" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># show our by hand analysis of variance</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aov_by_hand</span>(d_null<span class="sc">$</span>y, d_null<span class="sc">$</span>group)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum Sq</th>
<th style="text-align: right;">Mean Sq</th>
<th style="text-align: right;">F value</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">group</td>
<td style="text-align: right;">99</td>
<td style="text-align: right;">8637.85</td>
<td style="text-align: right;">87.25101</td>
<td style="text-align: right;">0.8724083</td>
<td style="text-align: right;">0.8134564</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">99900</td>
<td style="text-align: right;">9991165.48</td>
<td style="text-align: right;">100.01167</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
<p>This agrees with our previous calculation.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>aov_null <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">aov</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    y <span class="sc">~</span> group,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> d_null))[[<span class="dv">1</span>]]</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  aov_null</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum Sq</th>
<th style="text-align: right;">Mean Sq</th>
<th style="text-align: right;">F value</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">group</td>
<td style="text-align: right;">99</td>
<td style="text-align: right;">8637.85</td>
<td style="text-align: right;">87.25101</td>
<td style="text-align: right;">0.8724083</td>
<td style="text-align: right;">0.8134564</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">99900</td>
<td style="text-align: right;">9991165.48</td>
<td style="text-align: right;">100.01167</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># confirm calculates match</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">max</span>(<span class="fu">abs</span>(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aov_by_hand</span>(d_null<span class="sc">$</span>y, d_null<span class="sc">$</span>group) <span class="sc">-</span> </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summary</span>(<span class="fu">aov</span>(y <span class="sc">~</span> group, <span class="at">data =</span> d_null))[[<span class="dv">1</span>]]), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="sc">&lt;</span> <span class="fl">1e-7</span>)</span></code></pre></div>
<h3 id="an-analysis-of-variance-example-where-there-is-a-signal">An Analysis of Variance Example, Where There is a Signal</h3>
<p>Let's repeat our analysis on a data set where there is a relation between <code>group</code> and <code>y</code>.</p>
<p>We build our new data set. For some of the <code>group_levels</code> we are going to add a bit of a level-effect to <code>y</code>. This is what we would be looking for in either a linear model or in a clustering model. We are simulating the common modeling situation where knowing the group label is sometimes somewhat useful in predicting the outcome.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># start with no effect for any level </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>group_effect <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">length</span>(group_levels))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(group_effect) <span class="ot">&lt;-</span> group_levels</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># add an effect to first 25 group levels</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>effect_levels <span class="ot">&lt;-</span> group_levels[<span class="dv">1</span><span class="sc">:</span><span class="dv">25</span>]</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(level_name <span class="cf">in</span> effect_levels) {</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  group_effect[level_name] <span class="ot">&lt;-</span> (</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.4</span> <span class="sc">*</span> <span class="fu">ifelse</span>(</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">rbinom</span>(<span class="at">n =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> <span class="fl">0.5</span>) <span class="sc">&gt;</span> <span class="fl">0.5</span>,</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>      <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>))</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="co"># the new example data</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>d_effect <span class="ot">&lt;-</span> d_null</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>d_effect<span class="sc">$</span>y <span class="ot">&lt;-</span> d_null<span class="sc">$</span>y <span class="sc">+</span> group_effect[d_effect<span class="sc">$</span>group]</span></code></pre></div>
<p>Now that we have our new data, let's run an analysis of variance on it.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(<span class="fu">aov</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    y <span class="sc">~</span> group,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> d_effect))[[<span class="dv">1</span>]]</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum Sq</th>
<th style="text-align: right;">Mean Sq</th>
<th style="text-align: right;">F value</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">group</td>
<td style="text-align: right;">99</td>
<td style="text-align: right;">14347.85</td>
<td style="text-align: right;">144.9277</td>
<td style="text-align: right;">1.449108</td>
<td style="text-align: right;">0.002359</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">99900</td>
<td style="text-align: right;">9991165.48</td>
<td style="text-align: right;">100.0117</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># confirm by hand calculation matches</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">max</span>(<span class="fu">abs</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aov_by_hand</span>(d_effect<span class="sc">$</span>y, d_effect<span class="sc">$</span>group) <span class="sc">-</span> </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summary</span>(<span class="fu">aov</span>(y <span class="sc">~</span> group, <span class="at">data =</span> d_effect))[[<span class="dv">1</span>]]), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="sc">&lt;</span> <span class="fl">1e-7</span>)</span></code></pre></div>
<p>It may not seem so, but this is in fact better. From the new analysis of variance table we can see the <code>group</code> variable is explaining as a <code>14347.85 / (14347.85 + 9991165.48) = 0.0014</code> fraction of the overall variance. This is, unfortunately minuscule. However it <em>is</em> consistent with a small real effect or relation between <code>group</code> and <code>y</code>. The large F value and small significance confirm that this is a performance that is unlikely <em>if we assume</em> no relation is present.</p>
<p>The analysis of variance is supplying at least three very valuable services:</p>
<ul>
<li>It is estimating the overall quality of the model as an observed reduction in square error.</li>
<li>It is computing a significance of the above estimated model quality.</li>
<li>It can control what variables or sets of variables we attribute model quality to. In fact we can decompose the model's performance into an (order dependent) sequence of sub models or groups of variables.</li>
</ul>
<p>What this analysis shows: <em>is</em> there an effect among the variables or variable levels. But this does not show if there are specific levels responsible for the quality of the fit.</p>
<h3 id="what-not-to-do">What <strong>NOT</strong> To Do</h3>
<p>Now that we have seen an analysis of variance, let's use a much less powerful naive ad-hoc analysis. This is what one might attempt without analysis of variance type tools. The poor performance of this alternative is one of the justifications for incorporating analysis of variance into your workflow.</p>
<p>What the analysis of variance did well is: it assigned model quality to all the levels of a categorical variable as a <em>single</em> modeling step. What our inferior analysis will do is: attempt to assign model quality to individual variable levels. In other words, we are trying to find a best level explaining some fraction of model fit. This will, unfortunately, split what little explanatory power the <code>group</code> variable has across the levels. In addition this will invite in undesirable <a href="https://en.wikipedia.org/wiki/Multiple_comparisons_problem">multiple comparison issues</a> as one inspects the many estimated level effects. Together these issues give a test of low sensitivity, not able to effectively detect weak (but actual) effects or relations.</p>
<p>First let's fit a linear model on our first ("null") data.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>m_null <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  y <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> group,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> d_null)</span></code></pre></div>
<p>The "<code>0 +</code>" notation allows all levels of the categorical explanatory variable <code>group</code> to be tracked (normally one level is suppressed as the "reference" level). This fits a model that is a bit easier to explore. However it is known to <a href="https://win-vector.com/2017/06/15/an-easy-way-to-accidentally-inflate-reported-r-squared-in-linear-regression-models/">ruin the summary statistics</a>, so we will we not use the summary statistics from this fit.</p>
<p>Without the "<code>0 +</code>" notation the <code>lm()</code> summary does contain the same F-test as the analysis of variance. So the linear model <em>can</em> be used to directly identify if there is a significant fit.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># show linear model F test</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>lm_f_test <span class="ot">&lt;-</span> sigr<span class="sc">::</span><span class="fu">wrapFTest</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(y <span class="sc">~</span> group, <span class="at">data =</span> d_null))</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(sigr<span class="sc">::</span><span class="fu">render</span>(</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  lm_f_test,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">pLargeCutoff=</span><span class="dv">1</span>, <span class="at">format=</span><span class="st">&#39;markdown&#39;</span>))</span></code></pre></div>
<p><strong>F Test</strong> summary: (<i>R<sup>2</sup></i>=0.0008638, <em>F</em>(99,99900)=0.8724, <em>p</em>=0.8135).</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># confirm same values</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(lm_f_test<span class="sc">$</span>FValue <span class="sc">-</span> aov_null[<span class="dv">1</span>, <span class="st">&#39;F value&#39;</span>]) <span class="sc">&lt;</span> <span class="fl">1e-8</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(lm_f_test<span class="sc">$</span>pValue <span class="sc">-</span> aov_null[<span class="dv">1</span>, <span class="st">&#39;Pr(&gt;F)&#39;</span>]) <span class="sc">&lt;</span> <span class="fl">1e-8</span>)</span></code></pre></div>
<p>The fault in this scheme is <em>not</em> the linear modeling, but in ignoring the F-test and looking at the individual level fits too early. If all you want is the F-test, you can usually get that from the linear fit diagnostics without running an additional analysis of variance.</p>
<p>That being said: lets ignore the linear model F-test, and attempt (and fail) to use significance to filter down to some interesting variable levels.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pick our &quot;what is interesting&quot; threshold</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>significance_threshold <span class="ot">&lt;-</span> <span class="fl">0.05</span></span></code></pre></div>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># sort down to interesting coefficients or variables</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>null_coef <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(m_null)<span class="sc">$</span>coefficients,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">significance_threshold =</span> significance_threshold,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">check.names =</span> <span class="cn">FALSE</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>interesting_null_coef <span class="ot">&lt;-</span> null_coef[</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  null_coef[[<span class="st">&#39;Pr(&gt;|t|)&#39;</span>]] <span class="sc">&lt;</span> significance_threshold,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;Pr(&gt;|t|)&quot;</span>, <span class="st">&quot;significance_threshold&quot;</span>), </span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  drop <span class="ot">=</span> <span class="cn">FALSE</span>]</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">nrow</span>(interesting_null_coef) <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(interesting_null_coef)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Pr(&gt;|t|)</th>
<th style="text-align: right;">significance_threshold</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">grouplevel_012</td>
<td style="text-align: right;">0.0440619</td>
<td style="text-align: right;">0.05</td>
</tr>
<tr class="even">
<td style="text-align: left;">grouplevel_047</td>
<td style="text-align: right;">0.0147498</td>
<td style="text-align: right;">0.05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grouplevel_056</td>
<td style="text-align: right;">0.0281266</td>
<td style="text-align: right;">0.05</td>
</tr>
<tr class="even">
<td style="text-align: left;">grouplevel_060</td>
<td style="text-align: right;">0.0247010</td>
<td style="text-align: right;">0.05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grouplevel_066</td>
<td style="text-align: right;">0.0313065</td>
<td style="text-align: right;">0.05</td>
</tr>
</tbody>
</table>
<p>At first it appears that we have identified a few important variable levels. However, we (deliberately) neglected that when we are sifting through 100 variable levels looking for winners: we are subject to the <a href="https://en.wikipedia.org/wiki/Multiple_comparisons_problem">multiple comparisons problem</a>. Even if all the variables are useless (as they in fact are here), after inspecting 100 of them at a 5% significance we would expect to find about 5 false positives. By coincidence that is how many we found. So these "finds" are not numerous enough or strong enough to be considered convincing evidence there is a relation between "group" and "y" (which is just as well, as there is no such relation in this data set).</p>
<p>A correct procedure is to "apply a <a href="https://en.wikipedia.org/wiki/Bonferroni_correction">Bonferroni correction</a>." This is just saying "if you are looking at 100 things, you have to tighten up your significance criteria by a factor of 100." Let's do this.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tighten the filter using the Bonferroni correction</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>interesting_null_coef[<span class="st">&#39;Bonferroni corrected threshold&#39;</span>] <span class="ot">&lt;-</span> (</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  interesting_null_coef[<span class="st">&quot;significance_threshold&quot;</span>] <span class="sc">/</span> </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">length</span>(group_levels))</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>interesting_null_coef[<span class="st">&#39;still interesting&#39;</span>] <span class="ot">&lt;-</span> (</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  interesting_null_coef[[<span class="st">&#39;Pr(&gt;|t|)&#39;</span>]] <span class="sc">&lt;=</span> </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    interesting_null_coef[[<span class="st">&#39;Bonferroni corrected threshold&#39;</span>]])</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(interesting_null_coef)</span></code></pre></div>
<table>
<colgroup>
<col style="width: 15%" />
<col style="width: 12%" />
<col style="width: 23%" />
<col style="width: 30%" />
<col style="width: 18%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Pr(&gt;|t|)</th>
<th style="text-align: right;">significance_threshold</th>
<th style="text-align: right;">Bonferroni corrected threshold</th>
<th style="text-align: left;">still interesting</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">grouplevel_012</td>
<td style="text-align: right;">0.0440619</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">grouplevel_047</td>
<td style="text-align: right;">0.0147498</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grouplevel_056</td>
<td style="text-align: right;">0.0281266</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">grouplevel_060</td>
<td style="text-align: right;">0.0247010</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grouplevel_066</td>
<td style="text-align: right;">0.0313065</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
</tbody>
</table>
<p>There is no strong evidence of any relation between any <code>group</code> level and <code>y</code>. This is what was designed into this data, so it is a correct determination.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># confirm statement</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(interesting_null_coef[[<span class="st">&quot;still interesting&quot;</span>]] <span class="sc">==</span> <span class="cn">FALSE</span>))</span></code></pre></div>
<h3 id="why-to-not-do-what-we-just-showed">Why To Not Do What We Just Showed</h3>
<p>The Bonferroni Correction is "correct" in that it helps suppress false positive variables and variable levels. However, it sacrifices sensitivity. In fact it is so insensitive that this analysis procedure will fail to pick up small but true relations or effects in our other example.</p>
<p>Let's show the (bad) analysis on the data set where we <em>know</em> there is a relation.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># repeat the previous per-level analysis on new data</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>m_effect <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  y <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> group, </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> d_effect)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>effect_coef <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(m_effect)<span class="sc">$</span>coefficients,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">check.names =</span> <span class="cn">FALSE</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>interesting_effect_coef <span class="ot">&lt;-</span> effect_coef[</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  ((effect_coef[[<span class="st">&#39;Pr(&gt;|t|)&#39;</span>]] <span class="sc">&lt;</span> significance_threshold)) <span class="sc">|</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>    (<span class="fu">row.names</span>(effect_coef) <span class="sc">%in%</span> <span class="fu">paste0</span>(<span class="st">&quot;group&quot;</span>, effect_levels)),</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;Pr(&gt;|t|)&quot;</span>),</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  drop <span class="ot">=</span> <span class="cn">FALSE</span>]</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>interesting_effect_coef[<span class="st">&#39;Bonferroni corrected threshold&#39;</span>] <span class="ot">&lt;-</span> (</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  significance_threshold <span class="sc">/</span> <span class="fu">length</span>(group_levels))</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>interesting_effect_coef[<span class="st">&#39;still interesting&#39;</span>] <span class="ot">&lt;-</span> (</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>  interesting_effect_coef[[<span class="st">&#39;Pr(&gt;|t|)&#39;</span>]] <span class="sc">&lt;=</span> </span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>    interesting_effect_coef[[<span class="st">&#39;Bonferroni corrected threshold&#39;</span>]])</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(interesting_effect_coef)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Pr(&gt;|t|)</th>
<th style="text-align: right;">Bonferroni corrected threshold</th>
<th style="text-align: left;">still interesting</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">grouplevel_001</td>
<td style="text-align: right;">0.0754553</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">grouplevel_002</td>
<td style="text-align: right;">0.2257353</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grouplevel_003</td>
<td style="text-align: right;">0.0982440</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">grouplevel_004</td>
<td style="text-align: right;">0.2077323</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grouplevel_005</td>
<td style="text-align: right;">0.0933375</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">grouplevel_006</td>
<td style="text-align: right;">0.8127896</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grouplevel_007</td>
<td style="text-align: right;">0.2694684</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">grouplevel_008</td>
<td style="text-align: right;">0.8755393</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grouplevel_009</td>
<td style="text-align: right;">0.0013846</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">grouplevel_010</td>
<td style="text-align: right;">0.1767863</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grouplevel_011</td>
<td style="text-align: right;">0.3034294</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">grouplevel_012</td>
<td style="text-align: right;">0.0010999</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grouplevel_013</td>
<td style="text-align: right;">0.3760182</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">grouplevel_014</td>
<td style="text-align: right;">0.0428443</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grouplevel_015</td>
<td style="text-align: right;">0.0752557</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">grouplevel_016</td>
<td style="text-align: right;">0.8916944</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grouplevel_017</td>
<td style="text-align: right;">0.3126977</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">grouplevel_018</td>
<td style="text-align: right;">0.0524820</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grouplevel_019</td>
<td style="text-align: right;">0.3188409</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">grouplevel_020</td>
<td style="text-align: right;">0.0599345</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grouplevel_021</td>
<td style="text-align: right;">0.0582381</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">grouplevel_022</td>
<td style="text-align: right;">0.6620659</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grouplevel_023</td>
<td style="text-align: right;">0.0294470</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">grouplevel_024</td>
<td style="text-align: right;">0.0148508</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grouplevel_025</td>
<td style="text-align: right;">0.0021958</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">grouplevel_047</td>
<td style="text-align: right;">0.0147498</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grouplevel_056</td>
<td style="text-align: right;">0.0281266</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">grouplevel_060</td>
<td style="text-align: right;">0.0247010</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grouplevel_066</td>
<td style="text-align: right;">0.0313065</td>
<td style="text-align: right;">5e-04</td>
<td style="text-align: left;">FALSE</td>
</tr>
</tbody>
</table>
<p>Notice: none of the variables (including those that were actually doing something!) survived the Bonferroni corrected significance filter. The ad-hoc per-variable analysis method is not sufficiently sensitive. And this is why we suggest using analysis of variance instead of the per-variable or per-level attribution idea.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># confirm statement</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(interesting_effect_coef[[<span class="st">&quot;still interesting&quot;</span>]] <span class="sc">==</span> <span class="cn">FALSE</span>))</span></code></pre></div>
<p>If you want to evaluate model fit: directly evaluate model fit. And analysis of variance directly evaluates a total model fit summary statistic.</p>
<h2 id="discussion">Discussion</h2>
<p>Analysis of variance can be tricky to pin down and describe. That being said, let's try to say some things about analysis of variance.</p>
<ul>
<li>"... the analysis of variance, which may perhaps be called a statistical method, because the term is an a very ambiguous one- is not a mathematical theorem, but rather a convenient method of arranging the arithmetic." R. A Fisher 1934, as cited by Speed, "What is an Analysis of Variance?", Special Invited Paper, The Annals of Statistics, 1987, Vol 15, No 3, pp. 885-910.</li>
<li>Many good sources call the analysis of variance a generalization of a <a href="https://en.wikipedia.org/wiki/Student%27s_t-test">t-test</a> to more than two group levels (Horst Langer, Susanna Falsaperla and Conny Hammer, "Advantages and Pitfalls of Pattern Recognition Selected Cases in Geophysics", Volume 3 in Computational Geophysics 2020; Marc Kery, in "Introduction to WinBUGS for Ecologists", 2010; and others). Similar claims include: "just the case of regression for 0/1 variables" or "just the case of regression for truly orthogonal variables (arising from proper experiment design)."</li>
<li>The previous point itself is somewhat contradicted by claimed methods that appear to be mere applications of analysis of variance to clustering problems (analysis of variance's actual original domain!). For example: the the <a href="https://en.wikipedia.org/wiki/Calinski-Harabasz_index">Calinski-Harabasz index</a> from clustering is crypto-morphic to our friend the F-statistic.</li>
<li>A key additional feature of the analysis of variance is the crediting of explained variance to chosen variables or groups of variables (or more precisely to nested models). The convention is that model improvement is calculated in terms of the square-difference in nested model predictions, instead of in terms of the square reduction of prediction residuals. Under mild model optimality assumptions: these two quantities are identical. The second quantity is the one practitioners are likely to care about. The form of the first quantity likely helps derive of the number of degrees of freedom as used in the calculation.</li>
<li>The "variances" analyzed are possibly better described with less semantically loaded terms such as "dispersions" or "sums of square differences" (depending on the specialization). Speed, "What is an Analysis of Variance?", Special Invited Paper, The Annals of Statistics, 1987, Vol 15, No 3, pp. 885-910 states: "But all of this is just sums of squares- quadratic forms in normal variates if you wish; the only variance in sight is the common σ<sup>2</sup> and that does not appear to be undergoing any analysis."</li>
<li>There is overlap and competition between analysis of variance (Harris, Fisher ~ 1916 - 1925) and multiple linear regression (Galton, Pearson, Bravias ~ 1846 - 1930), (Gauss ~ 1821, Markov ~ 1900).</li>
</ul>
<h2 id="attribution-by-analysis-of-variance">Attribution by Analysis of Variance</h2>
<p>Analysis of variance becomes very useful when there are multiple variables and we want to attribute model utility down to the variables. This analysis depends on the order the variables are presented in, so it is contingent on user choices. This is inevitable as <a href="https://win-vector.com/2021/01/12/variable-utility-is-not-intrinsic/">variable utility is not intrinsic</a>.</p>
<p>A simple example is given here.</p>
<p>We set up our data.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># build new data set</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>m_rows <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>v_common <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> m_rows)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>v_1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> m_rows)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>v_2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> m_rows)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_1 =</span> v_common <span class="sc">+</span> v_1,</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_2 =</span> v_common <span class="sc">+</span> v_2,</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> v_common <span class="sc">+</span> v_1 <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> v_2 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="at">n =</span> m_rows)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>We then perform an analysis of variance.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(y <span class="sc">~</span> x_1 <span class="sc">+</span> x_2, <span class="at">data =</span> d)))</span></code></pre></div>
<pre><code>##               Df Sum Sq Mean Sq F value Pr(&gt;F)    
## x_1            1  20150   20150    8654 &lt;2e-16 ***
## x_2            1  25124   25124   10790 &lt;2e-16 ***
## Residuals   9997  23278       2                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>It is important to note: one can get the "percent credit" for each variable by checking what fraction of the "<code>Sum Sq</code>" column is associated with a given variable's row. In our case <code>x_2</code> is given more credit than <code>x_1</code> (larger <code>Sum Sq</code>, larger <code>F value</code>). Some of the credit assignment depends on user specified variable order, and not on properties of the model or data.</p>
<p>Let's confirm that.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(y <span class="sc">~</span> x_2 <span class="sc">+</span> x_1, <span class="at">data =</span> d)))</span></code></pre></div>
<pre><code>##               Df Sum Sq Mean Sq F value Pr(&gt;F)    
## x_2            1  43443   43443 18657.0 &lt;2e-16 ***
## x_1            1   1831    1831   786.2 &lt;2e-16 ***
## Residuals   9997  23278       2                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Now <code>x_2</code> is getting even more of the credit.</p>
<p>Which answer is "right" depends on "causal issues" that are domain specific and can't always be determined retrospectively from the data, as they depend on the actual semantics of the process producing the data. The "attribution depends on order" is an essential difficulty in attribution (though it may express in different ways with different tools). Roughly: the variable order is a very crude stand-in for a causal network diagram.</p>
<p>The analysis of variance attribution is very useful. In fact it is much more useful than model coefficient size, model coefficient significance, or even term sizes (coefficient times variable). However it is dependent on user specification of variable order, which can hinder interpretation.</p>
<h2 id="conclusion">Conclusion</h2>
<p>Analysis of variance is an analysis of overall model quality in terms of summed square differences. Under sufficient assumptions, it also gives a significance of fit estimate for the overall model. This is <em>without having to</em> attribute significance down to individual variables or levels. This makes the method useful in large data situations where model effects can often arise from a sum of small variable effects. In addition, the method is good at attributing model quality to user chosen variables or groups of variables (though in an order dependent manner).</p>
<p>Even for "something as simple as" linear models the analysis of variance attributions are much more reliable on attributions made by coefficient size, coefficient significance, or even so-called "terms" (<code>R</code> phrase for: coefficient times individual variables). So there are good reasons to consider analysis of variance style summaries.</p>
<p>The point of analysis of variance <em>can</em> be obscured by derivations that show that the traditional calculation tracks how nested models <em>differ from each other</em>, instead of directly tracking <em>how much nested models improve residual variance</em>. The two quantities <em>are identical given the usual orthogonality of residuals properties known to be true for linear modeling</em>. The confusion being: the first quantity makes for easier bookkeeping, while only the second quantity is inherently interesting to the analyst or data scientist. The identity of these two quantities is called out in the included example code at the "<code>confirm equal</code>" comment. Due to historic practice, we have a situation where implementations refer to "<a href="https://en.wikipedia.org/wiki/The_Scottish_play">The Scottish Play</a>", when users really want "Macbeth."</p>

