
---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->



```{r setup}
library("sparklyr")
#packageVersion('sparklyr')
library("dplyr")
#packageVersion('dplyr')
library("tidyr")

# Please see the following video for installation help
#  https://youtu.be/qnINvPqcRvE
# spark_install(version = "2.0.2")

# set up a local "practice" Spark instance
sc <- spark_connect(master = "local",
                    version = "2.0.2")
#print(sc)
```



```{r loaddata}
tableNames <- c("data_01", "data_02", "data_03")

# load the parquet files to register them
# to the Spark cluster.
# Could keep handles at this point, 
#  or get them with:
#   DBI::dbListTables(sc)/dplyr::tbl(sc, tableNamei)

readParquets <- function(tableNames) {
  tableCollection <- data_frame(tableName= tableNames)
  tableCollection$handle <- lapply(
    tableCollection$tableName,
    function(tableNamei) {
      spark_read_parquet(sc, tableNamei, tableNamei)
    }
  )
  tableCollection
}

tableCollection <- readParquets(tableNames)
print(tableCollection)
```

```{r finddata}
# or if we want to grab all tables
# sparklyr already knows about (note this can be expensive!):
tableNames <- DBI::dbListTables(sc)
```

A `data.frame` is a great place to keep what you know about 
your `Spark` handles in one place.  Let's add some details.

```{r adddetails}
addDetails <- function(tableNames) {
  tableCollection <- data_frame(tableName = tableNames)
  
  # get the references
  tableCollection$handle <-
    lapply(tableCollection$tableName,
           function(tableNamei) {
             dplyr::tbl(sc, tableNamei)
           })
  
  # and tableNames to handles for convenience
  # and printing
  names(tableCollection$handle) <-
    tableCollection$tableName
  
  # add in some details (note: nrow can be expensive)
  tableCollection$nrow <- vapply(tableCollection$handle, 
                                 nrow, 
                                 numeric(1))
  tableCollection$ncol <- vapply(tableCollection$handle, 
                                 ncol, 
                                 numeric(1))
  tableCollection
}

tableCollection <- addDetails(tableNames)

# convenient printing
print(tableCollection)

# look at the top of each table (also forces
# evaluation!).
lapply(tableCollection$handle, 
       head)
```

```{r buildcolumnmap}
columnDictionary <- function(tableCollection) {
  tableCollection$columns <- 
    lapply(tableCollection$handle,
           colnames)
  
  columnMap <- tableCollection %>% 
    select(tableName, columns) %>%
    unnest(columns)
  columnMap
}

columnMap <- columnDictionary(tableCollection)
print(columnMap)
```

```{r wrongwayto save}
# do not save handles, they are not really re-loadable
# in all situations.
saveRDS(tableCollection, 
        file='tableCollectionWrong.RDS')
```

```{r right way to save}
# save as CSV so users can edit it.
# re-derive all other columns later.
write.csv(tableCollection[ ,'tableName', drop=FALSE], 
          quote= FALSE,
          row.names = FALSE,
          file='tableCollection.csv')
```



```{r cleanup}
spark_disconnect(sc)
rm(list=ls())
gc()
```