---
title: "ExampleRun"
author: "Win-Vector LLC"
date: "June 1, 2016"
output:
  md_document:
    variant: markdown_github
---

Example showing vtreat varaible preperation followed by caret training.

```{r setup, message=FALSE,warning=FALSE,results=FALSE}
library('vtreat')
library('caret')
library('gbm')
library('doMC')
library('WVPlots') # see https://github.com/WinVector/WVPlots

# parallel for vtreat
ncores <- parallel::detectCores()
parallelCluster <- parallel::makeCluster(ncores)
# parallel for caret
registerDoMC(cores=ncores)
```

```{r loaddata}
# load data
# data from: http://archive.ics.uci.edu/ml/machine-learning-databases/adult/
colnames <-
  c(
    'age',
    'workclass',
    'fnlwgt',
    'education',
    'education-num',
    'marital-status',
    'occupation',
    'relationship',
    'race',
    'sex',
    'capital-gain',
    'capital-loss',
    'hours-per-week',
    'native-country',
    'class'
  )
dTrain <- read.table(
  'adult.data.txt',
  header = FALSE,
  sep = ',',
  strip.white = TRUE,
  stringsAsFactors = FALSE,
  na.strings = c('NA', '?', '')
)
colnames(dTrain) <- colnames
dTest <- read.table(
  'adult.test.txt',
  skip = 1,
  header = FALSE,
  sep = ',',
  strip.white = TRUE,
  stringsAsFactors = FALSE,
  na.strings = c('NA', '?', '')
)
colnames(dTest) <- colnames
```

```{r model, cache=TRUE}
# define problem
yName <- 'class'
yTarget <- '>50K'
varNames <- setdiff(colnames,yName)


# build varible encoding plan and prepare simulated out of sample
# training fame (cross-frame) 
# http://www.win-vector.com/blog/2016/05/vtreat-cross-frames/
cd <- vtreat::mkCrossFrameCExperiment(dTrain,varNames,yName,yTarget,
                                      parallelCluster=parallelCluster)
treatmentPlan <- cd$treatments
scoreFrame <- treatmentPlan$scoreFrame
dTrainTreated <- cd$crossFrame
# pick our variables
newVars <- scoreFrame$varName[scoreFrame$sig<1/nrow(scoreFrame)]
dTestTreated <- vtreat::prepare(treatmentPlan,dTest,
                                pruneSig=NULL,varRestriction=newVars)
print(newVars)

# train our model using caret
yForm <- as.formula(paste(yName,paste(newVars,collapse=' + '),sep=' ~ '))
# from: http://topepo.github.io/caret/training.html
fitControl <- trainControl(## 10-fold CV
  method = "cv",
  number = 3)
model <- train(yForm,
               data = dTrainTreated,
               method = "gbm",
               trControl = fitControl,
               verbose = FALSE)
print(model)
```

```{r score}
# apply predictions and plot
dTest$pred <- predict(model,newdata=dTestTreated,type='prob')[,yTarget]
WVPlots::ROCPlot(dTest,'pred',yName,'predictions on test')
WVPlots::DoubleDensityPlot(dTest,'pred',yName,'predictions on test')
confusionMatrix <- table(truth=dTest[[yName]],pred=dTest$pred>=0.5)
print(confusionMatrix)
testAccuarcy <- (confusionMatrix[1,1]+confusionMatrix[2,2])/sum(confusionMatrix)
testAccuarcy
```

Notice the achieved test accuarcy is in the ballpark of what was reported for this dataset.

    (From http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.names )
    Error Accuracy reported as follows, after removal of unknowns from
     |    train/test sets):
     |    C4.5       : 84.46+-0.30
     |    Naive-Bayes: 83.88+-0.30
     |    NBTree     : 85.90+-0.28

```{r cleanup}
# clean up
parallel::stopCluster(parallelCluster)
```


