---
title: "KDD2009vtreat"
author: "John Mount"
output: github_document
---


KDD2009 example using the `vtreat` `R` package. From https://github.com/WinVector/PDSwR2/blob/main/KDD2009/KDD2009vtreat.md


```{r kddexlibs, tidy=FALSE}
date()
#load some libraries
library('vtreat')
library('WVPlots') 
library('sigr')
library('parallel')
library('xgboost')


# generated/code/CodeExamples/c08_Advanced_Data_Preparation/00327_example_8.1_of_section_8.2.1.R 
# example 8.1 of section 8.2.1 
# (example 8.1 of section 8.2.1)  : Advanced Data Preparation : KDD and KDD Cup 2009 : Getting started with KDD Cup 2009 data 
# Title: Preparing the KDD data for analysis 

dir <- '/Users/johnmount/Documents/work/PracticalDataScienceWithR2nd/PDSwR2/KDD2009'

d <- read.table(paste(dir, 'orange_small_train.data.gz', sep = '/'),  	# Note: 1 
   header = TRUE,
   sep = '\t',
   na.strings = c('NA', '')) 	# Note: 2 
                                                
churn <- read.table(paste(dir, 'orange_small_train_churn.labels.txt', sep = '/'),
   header = FALSE, sep = '\t') 	# Note: 3 
d$churn <- churn$V1 	# Note: 4 

set.seed(729375) 	# Note: 5 
rgroup <- base::sample(c('train', 'test'), 	# Note: 6 
   nrow(d), 
   prob = c(0.9, 0.1),
   replace = TRUE)
dTrain <- d[rgroup=='train', , drop = FALSE]
dTest <- d[rgroup == 'test', , drop = FALSE]
                                                
outcome <- 'churn' 
vars <- setdiff(colnames(dTrain), outcome)
```

```{r}
write.csv(dTrain, file = 'kdd_2009_churn_train.csv', row.names = FALSE, quote = FALSE, na = '')
write.csv(dTest, file = 'kdd_2009_churn_test.csv', row.names = FALSE, quote = FALSE, na = '')
```

